name: Portfolio API Auto Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to AWS via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/portfolio/mydeployaztu
            git pull origin main
            if [ ! -d "venv" ]; then
              python3 -m venv venv
            fi
            ./venv/bin/pip install --upgrade pip
            ./venv/bin/pip install -r requirements.txt
            sudo cp portfolio-api.service /etc/systemd/system/portfolio-api.service
            sudo systemctl daemon-reload
            sudo systemctl enable portfolio-api
            sudo systemctl restart portfolio-api
            sudo systemctl restart nginx
